title = Toby Luanti Game
description = I am building a game from the ground up in Luanti as a personal project for learning and for fun.
author = Tobias Epp
release = 1
version = 0.1.0-dev
initial_privs = interact, shout, fly, fast, noclip, teleport, privs, give, settime, ban, kick, protection_bypass